MODEL:
  META_ARCHITECTURE: "MotionLearningModel"
  MAX_DEPTH: &max_depth 80
  POSE_NET:
    NAME: "GoogleMotionNet"
    USE_DEPTH: True
    GROUP_NORM: False
    MASK_MOTION: True
    LEARN_SCALE: True
    BURN_IN_ITERS: 20000
  WITH_MASK: True
LOSS:
  NUM_SCALES: 1
  SSIM_WEIGHT: 3.0
  C1: 'inf'
  C2: 0.000009
  CLIP: 0.0
  DEPTH_L1_WEIGHT: 0.0
  SMOOTHNESS_WEIGHT: 0.001
  SUPERVISED_WEIGHT: 0.0
  VARIANCE_FOCUS: 0.85
  VAR_LOSS_WEIGHT: 0.000
  MOTION_SMOOTHNESS_WEIGHT: 1.0
  MOTION_SPARSITY_WEIGHT: 0.2
  ROT_CYCLE_WEIGHT: 1e-3
  TRANS_CYCLE_WEIGHT: 5e-2
  SCALE_NORMALIZE: False
DATASETS:
  TRAIN:
    NAME: "WaymoDepth"
    DATA_ROOT: "/data2/data/waymo/training/image"
    DEPTH_ROOT: "/data2/data/waymo/training/depth"
    MASK_ROOT: "/data2/data/waymo/training/segmentation"
    SPLIT: "/data2/data/waymo/infos/training_infos.pkl"
    USE_CAMS: ['FRONT']
    DOWNSAMPLE: 2
    WITH_DEPTH: False
    WITH_POSE: False
    FORWARD_CONTEXT: 1
    STRIDE: 1
    PREPROCESS:
      - NAME: LoadImg
        WITH_CTX: true
      - NAME: LoadMask
      - NAME: CropTopTo
        IMG_H: 768
      - NAME: Resize
        IMG_W: 320
        IMG_H: 128
      - NAME: RandomFlip
      - NAME: RandomImageAug
      - NAME: ToTensor
  TEST:
    NAME: "WaymoDepth"
    DATA_ROOT: "/data2/data/waymo/validation/image"
    DEPTH_ROOT: "/data2/data/waymo/validation/depth"
    SPLIT: "/data2/data/waymo/infos/validation_infos.pkl"
    USE_CAMS: ['FRONT']
    DOWNSAMPLE: 20
    WITH_DEPTH: False
    WITH_POSE: False
    PREPROCESS:
      - NAME: LoadImg
      - NAME: LoadDepth
        KEEP_ORIG: true
      - NAME: ClipDepth
        MAX_DEPTH: *max_depth
      - NAME: CropTopTo
        IMG_H: 768
      - NAME: Resize
        IMG_W: 320
        IMG_H: 128
      - NAME: ToTensor

SOLVER:
  IMS_PER_BATCH: 16
  DEPTH_LR: 0.0002
  POSE_LR: 0.0002
  LR_STEPS: (8,16)
  GAMMA: 0.5
  MAX_EPOCHS: 20
  CHECKPOINT_PERIOD: 10
  CLIP_GRAD: 10
EVALUATORS: (
  "kitti_evaluator",
  "kitti_evaluator_0_30",
  "kitti_evaluator_30_50",
  "kitti_evaluator_50_80"
  )
TEST:
  GT_SCALE: True
VERSION: 2
LOG_PERIOD: 20