_BASE_: "./Base.yaml"

MODEL:
  DEPTH_NET:
    NAME: "DepthResNet"
    ENCODER_NAME: "18pt"
    UPSAMPLE_DEPTH: false
    RAMPUP_ITERS: -1
  POSE_NET:
    BURN_IN_ITERS: -1
SOLVER:
  IMS_PER_BATCH: 16
DATALOADER:
  NUM_WORKERS: 6
