_BASE_: "./Base.yaml"

MODEL:
  DEPTH_NET:
    NAME: "GoogleResNet"
    ENCODER_NAME: "18pt"
    UPSAMPLE_DEPTH: False
    LEARN_SCALE: False
    NORM: 'randLN'
    NOISE_STDDEV: 0.5
    RAMPUP_ITERS: 10000
  POSE_NET:
    SCALE_CONSTRAIN: "clip_ste"
SOLVER:
  IMS_PER_BATCH: 16
  LR_STEPS: (200,)
  GAMMA: 0.5
  MAX_EPOCHS: 200
DATALOADER:
  NUM_WORKERS: 8
