MODEL:
  META_ARCHITECTURE: "MonoDepth2Model"
  MAX_DEPTH: &max_depth 80
LOSS:
  SSIM_WEIGHT: 0.85
  C1: 0.0001
  C2: 0.0009
  CLIP: 0.0
  AUTOMASK: True
  SMOOTHNESS_WEIGHT: 0.001
  PHOTOMETRIC_REDUCE: 'min'
  SUPERVISED_WEIGHT: 0.0
  VARIANCE_FOCUS: 0.85
  VAR_LOSS_WEIGHT: 0.0000
DATASETS:
  TRAIN:
    NAME: "KittiDepthV2"
    DATA_ROOT: "/data/data/kitti/kitti_raw"
    DEPTH_ROOT: "/data/data/kitti/KITTI_raw_groundtruth"
    SPLIT: "/data/data/kitti/splits/eigen_train_files.txt"
    DEPTH_TYPE: "none"
    WITH_POSE: False
    FORWARD_CONTEXT: 1
    BACKWARD_CONTEXT: 1
    STRIDE: 1
    PREPROCESS:
      - NAME: LoadImg
        WITH_CTX: true
      - NAME: Resize
        IMG_W: 640
        IMG_H: 192
      - NAME: RandomFlip
      - NAME: RandomImageAug
      - NAME: ToTensor
  TEST:
    NAME: "KittiDepthV2"
    DATA_ROOT: "/data/data/kitti/kitti_raw"
    DEPTH_ROOT: "/data/data/kitti/KITTI_raw_groundtruth"
    SPLIT: "/data/data/kitti/splits/eigen_val_files.txt"
    DEPTH_TYPE: "groundtruth"
    WITH_POSE: False
    PREPROCESS:
      - NAME: LoadImg
      - NAME: LoadDepth
        KEEP_ORIG: true
      - NAME: ClipDepth
        MAX_DEPTH: *max_depth
      - NAME: Resize
        IMG_W: 640
        IMG_H: 192
      - NAME: ToTensor
SOLVER:
  IMS_PER_BATCH: 16
  DEPTH_LR: 0.0002
  POSE_LR: 0.0002
  LR_STEPS: (8,16)
  GAMMA: 0.5
  MAX_EPOCHS: 20
  CHECKPOINT_PERIOD: 1
EVALUATORS: (
  "kitti_evaluator",
  "kitti_evaluator_0_30",
  "kitti_evaluator_30_50",
  "kitti_evaluator_50_80"
  )
TEST:
  GT_SCALE: True
VERSION: 2
LOG_PERIOD: 20