MODEL:
  META_ARCHITECTURE: "SupDepthModel"
  MAX_DEPTH: &max_depth 80
LOSS:
  VARIANCE_FOCUS: 0.85
DATASETS:
  TRAIN:
    NAME: "WaymoDepth"
    DATA_ROOT: "/data2/data/waymo/validation/image"
    DEPTH_ROOT: "/data2/data/waymo/validation/depth"
    SPLIT: "/data2/data/waymo/infos/validation_infos.pkl"
    USE_CAMS: [ 'FRONT' ]
    WITH_DEPTH: True
    PREPROCESS:
      - NAME: LoadImg
      - NAME: LoadDepth
      - NAME: ClipDepth
        MAX_DEPTH: *max_depth
      - NAME: CropTopTo
        IMG_H: 768
      - NAME: RandomCrop
        IMG_W: 704
        IMG_H: 352
      - NAME: RandomFlip
      - NAME: RandomImageAug
      - NAME: ToTensor
  TEST:
    NAME: "WaymoDepth"
    DATA_ROOT: "/data2/data/waymo/training/image"
    DEPTH_ROOT: "/data2/data/waymo/training/depth"
    SPLIT: "/data2/data/waymo/infos/training_infos.pkl"
    USE_CAMS: [ 'FRONT' ]
    DOWNSAMPLE: 20
    WITH_DEPTH: True
    PREPROCESS:
      - NAME: LoadImg
      - NAME: LoadDepth
        KEEP_ORIG: true
      - NAME: ClipDepth
        MAX_DEPTH: *max_depth
      - NAME: CropTopTo
        IMG_H: 768
      - NAME: ToTensor
SOLVER:
  IMS_PER_BATCH: 16
  DEPTH_LR: 0.0001
  DEPTH_END_LR: 0.00001
  MAX_EPOCHS: 50
  CHECKPOINT_PERIOD: 1
EVALUATORS: (
  "kitti_evaluator",
  "kitti_evaluator_0_30",
  "kitti_evaluator_30_50",
  "kitti_evaluator_50_80"
  )
TEST:
  GT_SCALE: false
VERSION: 2
LOG_PERIOD: 20