MODEL:
  META_ARCHITECTURE: "SupDepthModel"
  MAX_DEPTH: &max_depth 80
LOSS:
  VARIANCE_FOCUS: 0.85
DATASETS:
  TRAIN:
    NAME: "KittiDepthV2"
    DATA_ROOT: "/data/data/kitti/kitti_raw"
    DEPTH_ROOT: "/data/data/kitti/KITTI_raw_groundtruth"
    SPLIT: "/data/data/kitti/splits/eigen_train_files.txt"
    DEPTH_TYPE: "groundtruth"
    PREPROCESS:
      - NAME: LoadImg
      - NAME: LoadDepth
      - NAME: ClipDepth
        MAX_DEPTH: *max_depth
      - NAME: KBCrop
      - NAME: RandomCrop
        IMG_W: 640
        IMG_H: 192
      - NAME: RandomFlip
      - NAME: RandomImageAug
      - NAME: ToTensor
  TEST:
    NAME: "KittiDepthV2"
    DATA_ROOT: "/data/data/kitti/kitti_raw"
    DEPTH_ROOT: "/data/data/kitti/KITTI_raw_groundtruth"
    SPLIT: "/data/data/kitti/splits/eigen_val_files.txt"
    DEPTH_TYPE: "groundtruth"
    PREPROCESS:
      - NAME: LoadImg
      - NAME: LoadDepth
        KEEP_ORIG: true
      - NAME: ClipDepth
        MAX_DEPTH: *max_depth
      - NAME: KBCrop
      - NAME: ToTensor
SOLVER:
  IMS_PER_BATCH: 16
  DEPTH_LR: 0.0001
  DEPTH_END_LR: 0.00001
  MAX_EPOCHS: 30
  CHECKPOINT_PERIOD: 1
EVALUATORS: (
  "kitti_evaluator",
  "kitti_evaluator_0_30",
  "kitti_evaluator_30_50",
  "kitti_evaluator_50_80"
  )
TEST:
  GT_SCALE: false
VERSION: 2
LOG_PERIOD: 20