_BASE_: "./Base.yaml"

MODEL:
  DATASET: "kitti"
  DEPTH_NET:
    NAME: "BtsModel"
    ENCODER_NAME: "resnet50_bts"
    BTS_SIZE: 512
    BN_NO_TRACK: false
    FIX_1ST_CONV: false
    FIX_1ST_CONVS: false
SOLVER:
  IMS_PER_BATCH: 8
  DEPTH_LR: 0.0002
  DEPTH_END_LR: 0.00001
DATALOADER:
  NUM_WORKERS: 6
LOG_PERIOD: 10